#!/bin/bash
# shellcheck disable=SC1090,SC2155,SC2086,SC2317
export VERSION=1.0.0
USAGE='foswiki-upgrade [options] install_dir old_release new_release
First, make a backup of your installation.
Copy your current running wiki installation into install_dir/
(lets call IR install_dir, OR old_release, NR new_release)
  rsync  -SHAaXx --delete --delete-excluded --force \
      root@webserver:/foswikidir/ ID/
Be sure to be able to modify it, e.g:
  sudo chmod -R a+rwX ID
Uncompress the old and new full distributions, from e.g. Foswiki-2.1.11.tgz
  tar xfz .../Foswiki-2.1.10.tgz; tar xfz .../Foswiki-2.1.11.tgz
  (then OR will be Foswiki-2.1.6 and NR Foswiki-2.1.11)
See what will be merged:
  foswiki-upgrade ID OR NR
Perform the upgrade:
  foswiki-upgrade -y IS OR NR
Then deploy
  rsync  -SHAaXx --delete --delete-excluded --force \
      ID/ root@webserver:/foswikidir/ ID/
  ssh root@webserver chown -R web-user:web-group /foswikidir
Test it!

This script supposes a modern version of Foswiki (v2+): it overwrites blindly
the files that should not have been modified, so when customizing your wiki be
sure to never directly modify distributed files.

The script however will not overwrite blindly any topic file that has been
edited via Foswiki itself, by checking the author metadata. It will perform a
3-way merge, as automated as possible.

It also works only on a local copy of the site. You will have to download
yourself a copy of your site, upgrade, and then re-upload it in place.
This keeps the script simpler and safer.

It works on linux, but should work in linux-like layers on top of other OSes,
such as cygwin, WSL, Homebrew, ...

Options:
  -y      yes, do perform the merges, otherwise do nothing,
          just print the files needing a merge.
  -T DIR  uses DIR instead of tmp to store temporary files.
  -kd3    uses kdiff3 to perform automatic merges, reverting to interactive
          only on conflicts (default).
  -kd3i   uses kdiff3 but always in interactive mode.
  -xxd    uses xxdiff to perform interactive merges.
  -tkd    uses tkdiff to perform interactive merges.
  -mp PROG   merge program to use, will be called with args: OR ID NR.
  -v      verbose mode.
Version 1.0.0 - 2026-03-26 - (c) 2026 Colas Nahaboo.
'

rsync-mirror () { rsync  -SHAaXx --delete --delete-excluded --force "$@";}
requires () {
    local c
    for c in "$@"; do
        command -v "$c" >/dev/null || err "required '$c' not found"
    done
}
requires realpath rsync

# Options default values:
merge=merge_kdiff3
merge_prog=
tmp=/tmp
doit=false

# Options processing
# shellcheck disable=SC2015,SC2016,SC2034,SC2046,SC2089,SC2090,SC2219,SC2317
{ E(){ echo "$@">&2;};En(){ E -n "$@";};warn(){ E "###Warning: $*">&2;};V(){ :;}
T(){ :;};v=false;err(){ E "***ERROR: $*">&2;exit 1;};nl=$'\n';_g='[ -n "$_a" ]&&
OPTARG="${_a#=}"||{ let _n++;OPTARG="${@:$_n:1}";}';HASARG='eval eval "$_g";
let "_n>$#"&&err Missing arg: $1';while [[ $1 =~ ^-(-?[?[:alnum:]]+)(=.*)?$ ]]
do _s="${BASH_REMATCH[1]}";_a="${BASH_REMATCH[2]}";_n=1;[[ $_s =~ ^- ]]&&{ _o=\
${_s:1};_s=;}||{ _o=${_s:0:1};_s=${_s:1};};while [ -n "$_o" ];do case "$_o" in
#----options start-------------------------------------------------------------
  kd3) merge=merge_kdiff3;; 
  kd32) merge=merge_kdiff3i;; 
  tkd) merge=merge_tkdiff;;
  xxd) merge=merge_xxdiff;;
  mld) merge=merge_meld;;
  T) tmp="$OPTARG";;
  y) doit=true;;
  mp) merge=merge_; merge_prog="$OPTARG";;
#----options end---------------------------------------------------------------
v)T(){ local i;En "==";for i in "$@";do [[ $i =~ [^_[:alnum:]] ]]&&En " $i"||
En " $i=${!i}";done;E;};V(){ E "== $*";};v=true;;h|\?)E "$USAGE";exit;;*)err \
"Bad option: $1";exit 1;;esac;_o=${_s:0:1};_s=${_s:1};_a=;done;shift $_n;done;}
#----end of https://github.com/ColasNahaboo/bashoptions------------------v1.0.1

###################### checks
(($# == 3)) || err "3 dir arguments needed: installed old new"
for d in "$@"; do
    [[ -e $d/lib/Foswiki.pm ]] || err "Not a Foswiki dir: $d"
done
[[ $merge =~ ^merge_(.*) ]] && requires "${merge#*_}"
[[ -d "$tmp" ]] || err "'$tmp' is not a directory"
I="$1"                          # CURRENT INSTALL
O="$2"                          # OLD RELEASE OF INSTALL
U="$3"                          # UPDATE-TO RELEASE
B="$tmp/foswiki-backup-$(date +%Y-%m-%d.%Hh%M)" # BACKUP DIR

# check I is actually the same version as O
version_of () {
    grep -oP "\$VERSION *= *version->declare[(]'\K[^']*" "$1/lib/Foswiki.pm"
}
I_v=$(version_of $I)
O_v=$(version_of $O)
[ "$I_v" != "$O_v" ] && err "install_dir is not based on old_release:
  $I is VERSION $I_v, and $O is $O_v"

I=$(realpath "$I")
O=$(realpath "$O")
U=$(realpath "$U")
tmp=$(realpath "$tmp")

# merge args are 3 versions of a file argument in dirs: O I U
merge_kdiff3  () { kdiff3 -m --auto $O/$1 $I/$1 $U/$1 -o $I/$1; }
merge_kdiff3i () { kdiff3 -m $O/$1 $I/$1 $U/$1 -o $I/$1; }
merge_tkdiff  () { tkdiff -a $O/$1 -o $I/$1 $I/$1 $U/$1; }
merge_xxdiff  () { xxdiff --show-merged-pane -O -m -M $I/$1 $I/$1 $O/$1 $U/$1; }
merge_meld    () { meld $O/$1 $I/$1 $U/$1; }
merge_        () { $merge_prog $O/$1 $I/$1 $U/$1;}

###################### Functions

main () {
    local i
    $doit && rsync-mirror "$I" "$B"      # first, backup
    cd $U || exit 1
    # first, force upgrade of files that should be untouched
    for i in bin/*; do
        [[ "$i" == bin/configure ]] &&  continue
        copy "$i" "$I/$i"
    done
    for i in lib/*; do
        [[ "$i" == "lib/LocalSite.cfg" ]] && continue
        copy "$i" "$I/$i"
    done
    for i in *; do
        [[ $i =~ ^(bin|lib|data)$ ]] && continue
        copy "$i" "$I"
    done
    cp data/mime.types $I/data
    merge bin/configure
    merge lib/LocalSite.cfg
    # overwrite all unedited topic files in data/, the ones with header still:
    # %META:TOPICINFO{author="ProjectContributor"
    while read -r i; do
        if [[ $(auth "$I/$i" ProjectContributor) == ProjectContributor ]]; then
            $doit || continue
            copy "$i" "$I/$i"
        else                    # merge!
            merge "$i"
        fi
    done < <(find data -type f -name \*.txt)
    echo "Done."
    $doit && echo "Backup copy if needed: $B"
}

copy(){
    local file="$1" dest="$2" dir="${2%/*}"
    [[ -z "$2" ]] && err "EMPTY: copy $*"
    $doit || { echo "  $file"; return;}
    V "copy $file $2"
    mkdir -p "$dir"
    cp -r "$file" "$dest"
}

merge(){
    $doit || { echo "  $1"; return;}
    [[ -z "$1" ]] && err "EMPTY merge"
    echo "============== $merge: $1"
    $merge "$1"
}

auth(){
    local topic="$1" default="$2"
    [[ -s "$topic" ]] || { echo "$default"; return;}
    grep -oPm1 '^%META:TOPICINFO[{].*author="\K[^"]*' "$topic"
}

main

exit 0
